name: CI Pipeline

on: [pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements-dev.txt

      - name: Run lint
        run: |
          python -m black --check .
      - name: Build docs
        run: |
          python -m sphinx -W --keep-going docs/ docs/_build
      - name: Store built documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: qst-pr-docs
          path: |
            ./docs/_build/*
            !**/.doctrees
            !**/.buildinfo
          if-no-files-found: error
  
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.8]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements-dev.txt

      - name: Run tests
        env:
          QISKIT_IBM_TOKEN: ${{ secrets.QISKIT_IBM_TOKEN }}
        run: |
          python -m pytest .
